export enum UserRole {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
}

export enum PostType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  PDF = 'PDF',
  ASSIGNMENT = 'ASSIGNMENT',
  QUIZ = 'QUIZ',
  LESSON = 'LESSON',
  POLL = 'POLL',
}

export enum PostVisibility {
  PUBLIC = 'PUBLIC',
  FRIENDS = 'FRIENDS',
  GROUP = 'GROUP',
  COURSE = 'COURSE',
  PRIVATE = 'PRIVATE',
}

export enum PostStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ReactionType {
  LIKE = 'LIKE',
  LOVE = 'LOVE',
  CARE = 'CARE',
  HAHA = 'HAHA',
  WOW = 'WOW',
  SAD = 'SAD',
  ANGRY = 'ANGRY',
}

export enum FriendRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

export enum GroupType {
  SCHOOL = 'SCHOOL',
  CLASSROOM = 'CLASSROOM',
  CLUB = 'CLUB',
}

export enum CourseLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum SubmissionStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
  LATE = 'LATE',
}

export enum NotificationType {
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  MESSAGE = 'MESSAGE',
  HOMEWORK = 'HOMEWORK',
  EXAM = 'EXAM',
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  AI_TASK = 'AI_TASK',
  GROUP = 'GROUP',
  COURSE = 'COURSE',
}

export enum CalendarEventType {
  HOMEWORK = 'HOMEWORK',
  EXAM = 'EXAM',
  EVENT = 'EVENT',
  LIVE_CLASS = 'LIVE_CLASS',
}

export enum MediaStatus {
  UPLOADING = 'UPLOADING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum MediaCategory {
  AVATAR = 'AVATAR',
  COVER_PHOTO = 'COVER_PHOTO',
  STORY_IMAGE = 'STORY_IMAGE',
  STORY_VIDEO = 'STORY_VIDEO',
  POST_IMAGE = 'POST_IMAGE',
  POST_VIDEO = 'POST_VIDEO',
  POST_PDF = 'POST_PDF',
  POST_DOCUMENT = 'POST_DOCUMENT',
  ASSIGNMENT_FILE = 'ASSIGNMENT_FILE',
  HOMEWORK_FILE = 'HOMEWORK_FILE',
  COURSE_MATERIAL = 'COURSE_MATERIAL',
  COURSE_THUMBNAIL = 'COURSE_THUMBNAIL',
  MARKETPLACE_IMAGE = 'MARKETPLACE_IMAGE',
  AI_GENERATED = 'AI_GENERATED',
  MESSAGE_ATTACHMENT = 'MESSAGE_ATTACHMENT',
  CHAT_FILE = 'CHAT_FILE',
}
